name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production, preview]
    environment: ${{ matrix.environment }}

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
      TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
      TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
      SKIP_ENV_VALIDATION: true

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    # - name: Run tests
    #   run: npm test
      
    - name: Build
      run: npm run build

    - name: Debug Environment Variables
      run: |
        echo "DATABASE_URL is set: ${{ env.DATABASE_URL != '' }}"
        echo "NEXTAUTH_SECRET is set: ${{ env.NEXTAUTH_SECRET != '' }}"
        echo "NEXTAUTH_URL is set: ${{ env.NEXTAUTH_URL != '' }}"
        echo "DISCORD_CLIENT_ID is set: ${{ env.DISCORD_CLIENT_ID != '' }}"
        echo "DISCORD_CLIENT_SECRET is set: ${{ env.DISCORD_CLIENT_SECRET != '' }}"
        echo "GITHUB_CLIENT_ID is set: ${{ env.GITHUB_CLIENT_ID != '' }}"
        echo "GITHUB_CLIENT_SECRET is set: ${{ env.GITHUB_CLIENT_SECRET != '' }}"
        echo "TWITTER_CLIENT_ID is set: ${{ env.TWITTER_CLIENT_ID != '' }}"
        echo "TWITTER_CLIENT_SECRET is set: ${{ env.TWITTER_CLIENT_SECRET != '' }}"